# _config.yml

theme : "Cayman"
# remote_theme           : "j2doll/minimal-mistakes"
# url                      : https://j2doll.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
# baseurl                  : "" # the subpath of your site, e.g. "/blog"
